modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
modId="creepernuggets"
entryClass="vpzomtrrfrt.creepernuggets.CreeperNuggets"
version="${file.jarVersion}"
authors=["vpzom"]
credits=["TevaVejo on CurseForge for the idea"]
